### ISSUE TITLE
Permission tests no longer working with the offline mode added

### ISSUE THREAD

**Issue by dayan9265** [cook4me/android#250]
ch.epfl.sdp.cook4me.ui.map.TestMapPermissionWrapper > assertMapIsDisplayedWhenLocationIsEnabled[Pixel_XL_API_33_2(AVD) - 13] FAILED 
        java.lang.NoSuchMethodError: No virtual method Boolean$param-isOnline$fun-MapPermissionWrapper()Z in class Lch/epfl/sdp/cook4me/ui/map/LiveLiterals$MapPermissionWrapperKt; or its super classes (declaration of 'ch.epfl.sdp.cook4me.ui.map.LiveLiterals$MapPermissionWrapperKt' appears in /data/app/~~k9VZ6JOiuXu6wrx7GJpOQw==/ch.epfl.sdp.cook4me.test-eb1Y5IW111INla7BIFbu4w==/base.apk!classes11.dex)
        at ch.epfl.sdp.cook4me.ui.map.MapPermissionWrapperKt.MapPermissionWrapper(MapPermissionWrapper.kt:16)

ch.epfl.sdp.cook4me.ui.map.TestMapPermissionWrapper > assertMapIsNotDisplayedWhenLocationIsNotEnabled[Pixel_XL_API_33_2(AVD) - 13] FAILED 
        java.lang.NoSuchMethodError: No virtual method Boolean$param-isOnline$fun-MapPermissionWrapper()Z in class Lch/epfl/sdp/cook4me/ui/map/LiveLiterals$MapPermissionWrapperKt; or its super classes (declaration of 'ch.epfl.sdp.cook4me.ui.map.LiveLiterals$MapPermissionWrapperKt' appears in /data/app/~~k9VZ6JOiuXu6wrx7GJpOQw==/ch.epfl.sdp.cook4me.test-eb1Y5IW111INla7BIFbu4w==/base.apk!classes11.dex)
        at ch.epfl.sdp.cook4me.ui.map.MapPermissionWrapperKt.MapPermissionWrapper(MapPermissionWrapper.kt:16)

**Comment by bu-da** [comment]
Could maybe help? https://stackoverflow.com/questions/76106083/java-lang-nosuchmethoderror-no-virtual-method-setcontentlkotlin-jvm-functions
