### ISSUE TITLE
General refactoring: extract common components, restructure project, define common components

### ISSUE THREAD

**Issue by bu-da** [cook4me/android#57]
Additional points:
* Logging: e.g. https://github.com/cook4me/android/pull/55#discussion_r1138814604
* General exception handling: e.g. https://github.com/cook4me/android/pull/55#discussion_r1138859434
* Document all public functions? 
* Group strings together, may create new string.xml per feature
* Get rid of Android linter warnings

**Comment by pauromeu** [comment]
[Prepare demo sprint 2 - cook4me_android - Code Climate.pdf](https://github.com/cook4me/android/files/10991622/Prepare.demo.sprint.2.-.cook4me_android.-.Code.Climate.pdf)
